name: Integration testing
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
jobs:
  test:
    strategy:
      matrix:
        include:
          - os: macos-12
          - os: windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Python dependencies
        run: "pip install requests==2.31.0"

      - name: Set up cargo cache
        uses: actions/cache@v3
        continue-on-error: false
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: ${{ runner.os }}-cargo-

      - name: Build target binary
        run: "cargo build --bin harmonia"

      - name: Run integration tests
        run: python tests/integration.py
