name: Release for all supported platforms
permissions:
  contents: write
on:
  push:
    tags:
      - '[0-9]\.[0-9]\.[0-9]'
jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: taiki-e/create-gh-release-action@v1
        with:
          changelog: CHANGELOG.md
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-20.04 # We choose Ubuntu 20.04 to have pretty good support with GLIBC version (limiting factor)
          - target: x86_64-apple-darwin
            os: macos-12
          - target: x86_64-pc-windows-msvc
            os: windows-2022
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Required Linux dependencies
        if: runner.os == 'Linux'
        run: "sudo apt install -y libasound2-dev"
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: harmonia
          target: ${{ matrix.target }}
          tar: unix
          zip: windows
          token: ${{ secrets.GITHUB_TOKEN }}
